let translateData = {
    rus: {
        headerTitle: 'Мы ищем мастеров маникюра и педикюра, в команду L&B',
        inputDesc: 'Мы не передаём вашу почту третьим лицам и не рассылаем спам',
        popupReady: 'Готово!',
        popupText: 'Будем держать Вас в курсе всех новостей а также вы первым узнаете о старте нащего сервиса)',
        popupFooter: 'Мы Вас не подведём!',
        aboutTitle: 'Что такое L&B',
        aboutText: 'L&B это важнейший инcтрумент для твоего бизнеса, который поможет найти новых клиентов, получить бесплатно нужные рекомендации от лучших экспертов западного рынка, повысить уровень своей квалификации, получить признание и даже стать одним из экспертов европейских брендов. Становись лучшим вместе с нами!',
        whatTitle: 'Что мне даст работа с L&B',
        whatText1_title: 'Больше клиентов',
        whatText1: 'Возможность принимать дополнительных клиентов в свободное время, мы даем возможность зарабатывать больше!',
        whatText2_title: 'Честные отзывы',
        whatText2: 'Доверие и репутацию на L&B обеспечивают отзывы, которые посетители и мастера оставляют отзыв друг на друга по завершению каждого сеанса. Вы можете посмотреть отзывы еще до того как клиент придет к вам.',
        whatText3_title: 'Проверенные клиентов',
        whatText3: 'Перед бронированием посетители должны предоставить определенную информацию о себе, например подтвержденный номер телефона и электронный адрес, в качестве других мер безопасности, вы можете установить условие, чтоб у клиентов были рекомендации других мастеров и подтвержденный профиль.',
        helpTitle: 'Контроль над приемом в ваших руках',
        helpTab1: 'Таймлайн',
        helpTab1_title: 'Принимай клиентов в удобное для себя время',
        helpTab2: 'Прайс',
        helpTab2_title: 'Устанавливай свои цены',
        helpTab3: 'Будь свободным',
        helpTab3_title: 'Ваш кабинет - ваши правила',
        reviewsTitle: 'Вы в хороших руках',
        reviewsSubTitle: 'У нас размещаются только реальные отзывы пользователей системы',
        footerTitle: 'Зарабатывай вместе с нами!',
        footerText: 'Присоеденяйся к нам, и измени рынок бьюти индустрии Украины',
        footerLinkMain: 'Главная',
        footerLinkTermsOfUse: 'Пользовательское соглашение'
    },
    eng: {
        headerTitle: 'We are looking for manicure and pedicure masters for L&B team',
        inputDesc: 'We do not forward your email to third parties and do not send spam.',
        popupReady: 'Done!',
        popupText: 'We will keep you up to date with all the news and also you will be the first to know about the launch of our service.)',
        popupFooter: 'We will not let you down!',
        aboutTitle: 'What is L&B',
        aboutText: 'This is the most important tool for your business, which will help you find new clients, get the necessary recommendations for free from the best experts of the western market, improve your qualifications, gain recognition and even become one of the experts of European brands. Become the best with us!',
        whatTitle: 'What L&B gives me',
        whatText1_title: 'More clients',
        whatText1: 'The ability to take additional customers in your free time, we give you the opportunity to earn more!',
        whatText2_title: 'Честные отзывы',
        whatText2: 'The credibility and reputation at L & B provide feedback that visitors and masters leave feedback on each other at the conclusion of each session. You can see the reviews before the client comes to you.',
        whatText3_title: 'Проверенные клиентов',
        whatText3: 'Before booking, visitors must provide certain information about themselves, such as a confirmed phone number and email address, as other security measures, you can set a condition so that customers have recommendations from other masters and a confirmed profile.',
        helpTitle: 'Reception control in your hands',
        helpTab1: 'Timeline',
        helpTab1_title: 'Accept customers at a convenient time',
        helpTab2: 'Price',
        helpTab2_title: 'Set your prices',
        helpTab3: 'Be free',
        helpTab3_title: 'Your account - your rules',
        reviewsTitle: 'You are in good hands',
        reviewsSubTitle: 'We have only real reviews of users of the system.',
        footerTitle: 'Earn with us!',
        footerText: "Join us, and change the market of beauty industry in Ukraine",
        footerLinkMain: 'Main',
        footerLinkTermsOfUse: 'Terms of use'
    }
 
}
export default translateData;